In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [19]:
b = np.array([14,2,18,6,12,3,11,7,5,6,25,20,23,35,26])
c = b.reshape(5,3)

In [20]:
c

array([[14,  2, 18],
       [ 6, 12,  3],
       [11,  7,  5],
       [ 6, 25, 20],
       [23, 35, 26]])

In [25]:
np.argsort(c,axis=0)

array([[1, 0, 1],
       [3, 2, 2],
       [2, 1, 0],
       [0, 3, 3],
       [4, 4, 4]], dtype=int64)

In [26]:
np.argmin(c)

1

In [27]:
np.argmax(c)

13