# Basic Functions

In [1]:
import numpy as np
array1 = np.array([[10,20,30,40.1,50],[60,70,80,90,100]],dtype = 'int32')
print(array1)
print(type(array1))

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.zeros((6))

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((6)).dtype

dtype('float64')

In [7]:
np.ones(6)


array([1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(6).dtype

dtype('float64')

In [9]:
array1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [10]:
array1*array1

array([[  100,   400,   900,  1600,  2500],
       [ 3600,  4900,  6400,  8100, 10000]])

In [11]:
array1+array1

array([[ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200]])

In [12]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
array1**array1

array([[1410065408,          0, 1073741824,          0,          0],
       [         0,          0,          0,          0,          0]])

In [14]:
12**12

8916100448256

In [15]:
np.array([12111*1211])

array([14666421])

In [16]:
np.array([12111.000*1211],dtype='int64')

array([14666421], dtype=int64)

In [17]:
np.array([12111.000*1211],dtype='int32')

array([14666421])

In [18]:
1/array1

array([[0.1       , 0.05      , 0.03333333, 0.025     , 0.02      ],
       [0.01666667, 0.01428571, 0.0125    , 0.01111111, 0.01      ]])

# Slicing

In [19]:
array2 = np.array([10,20,30,40,50,60])

In [20]:
arr = array2[4:6].copy()

In [21]:
arr

array([50, 60])

In [22]:
arr[0] = 100

In [23]:
array2

array([10, 20, 30, 40, 50, 60])

In [24]:
array1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [28]:
array1[0,2]

30